# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('joining_date', models.DateField(blank=True)),
                ('Joined_date', models.DateField(blank=True)),
                ('Termination_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated')], max_length=100)),
                ('present_address', models.TextField(max_length=300)),
                ('permanent_address', models.BooleanField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('C+', 'C+'), ('C-', 'C-')], max_length=30)),
                ('home_phone', models.IntegerField(max_length=100)),
                ('Cell_phone', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_person', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=100)),
                ('driving_license_no', models.IntegerField(max_length=100)),
                ('emp_package', models.CharField(max_length=100)),
                ('base_salary', models.IntegerField(blank=True, max_length=100)),
                ('variable_salary', models.IntegerField(blank=True, max_length=100)),
                ('provide_accommodation', models.BooleanField()),
                ('provide_trans', models.BooleanField()),
                ('emp_type', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Contractor', 'Contractor')], max_length=100)),
                ('emp_dept', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=100)),
                ('emp_manager_name', models.CharField(max_length=100)),
                ('emp_group', models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('administrators', 'Administrators'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('it', 'IT')], max_length=100)),
            ],
        ),
    ]
