# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20170419_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Joined_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Cell_phone',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Termination_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_no',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_dept',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_manager_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_package',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_no',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
